language: ruby
rvm:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
before_install:
- yes | gem update --system --force
- gem install bundler
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: DWA8Omki8LvTEIbm8XRSvpgTLaAxO/0JYzlpZAkivg+83ysBOu7Sc2CtjVid8DxZhDKh54UUZqAay6tGZns+WKWMhCmvLaLIYkE67EYtXZkAQVmG39c7QWQyjqixqVEU7zmjTPT3JwJwEMRMObG1id/Qkk2A2DUmdG7Q5JGAYovtWoKn5r8XwFZCBY9Z6C39KNNTRSNzlKBrcznwPTNWUsJlod9jOc+MkPmX3UkFzQ9qFikHF240JF96BEMrCMR99yh8A1w24FMAXadFsT8LUrrddTWThJW8enVb/CNI8aguuFLLETdvIS5RM9w4idxhsMLI+dVz2cnlyGMSVfkpfCTkhtpvwv0JcJxEIIjjRzxQt6GA5No4cmPcC1p4SMbBCK6xudV+8A4z25B1XM7pgRztOV7/xH0tD6PKsyTuonTFwq2mqGaZflfG+J5ybTFu9Qoq67cHGqEaYLBrqncb1XnbQOGzaVvhRh4h4FCMr/7pV94KG0jMlOyrNrkS0LtiSpHW4EUPE+x//0F9bI2TiuWcEo0XKCjBmMzwZI0N19erayYjYI6qE/5Dv2NfwghvvvWinBEbpa+SXebt4siqqjyEOjKf2vq4XtRwPVPiBiOB5N4cP3A+xbT9GTfF7BSadGOLXYgClOW0MIgrrBocxGfFuU5r63N3qj2up5yxgrU=

  app: crime-time
  run: rails db:migrate db:seed
